descriptor-schema-version: "2.0"
info:
  author-link: "http://www.cisco.com/"
  author-name: "Mike Maas"
  description: "An example application showing how to use package_config.ini"
  name: "app-config"
  version: "1.0"

app:
  type: paas
  resources:
    profile: c1.small
    network:
      -
        interface-name: eth0
        ports:
          tcp:
            - 8000

    recommendations:
      -
        description: "This test application at most requires a profile of c1.small"
        label: "Configuration Example Application"
        profile: c1.small

  startup:
    runtime: python
    runtime-version: 2.7.3
    target: main.py
